### ISSUE TITLE
Amend homepage design to only show news and events

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye#32]
The team from SYE indicated that we used the wrong mockup design for the staging site (I probably got confused) so we need to make some small changes to the central section, which currently looks like this:

![screen shot 2016-03-21 at 08 34 48](https://cloud.githubusercontent.com/assets/4170351/13913557/ef378498-ef3f-11e5-8348-828ba100015e.png)

The central section should be changed to resemble this, showing only news and events:

![sye mock-up 1](https://cloud.githubusercontent.com/assets/4170351/13913566/0350fd2e-ef40-11e5-924e-8f8c99ad76c6.jpg)

**Comment by zarino** [comment]
When you say it should look like this, what exactly are you expecting to be shown under the headings?

![0350fd2e-ef40-11e5-924e-8f8c99ad76c6](https://cloud.githubusercontent.com/assets/739624/14560599/b55868c8-0308-11e6-85d5-fcdae8942a83.jpg)

We currently display some explanatory text (eg: "Get updates on top stories…" and "Participate and join other #ActiveCitizens at…") – are you saying you want that text to be replaced with a list of news stories and events?

**Comment by JenMysoc** [comment]
@zarino they would like to show at minimum the most recent events and news articles from the relevant pages within the site (there are separate pages at http://staging.shineyoureye.org/info/events and http://staging.shineyoureye.org/blog/ )

**Comment by JenMysoc** [comment]
@zarino for the news; it would be great if it could be handled similar to the way that PA handles pulling in links to blog posts; by providing a summary snapshot of the text. Same with events

**Comment by zarino** [comment]
@JenMysoc – cutting the 4 columns down to 2 is dead simple.

But changing the static text to instead be a list of blog posts and events will need a developer. I can get a list of recent blog posts fairly easily. But from what I can tell, the site currently has no concept of "events" – and I'm assuming you don't want them hard-coded into the template – so you’ll need to decide how the SYE team expects to be able to edit this list of events as time passes.

**Comment by JenMysoc** [comment]
That's fine. This is still a prototype for them so we can do those connecting bits when I've sent them the design looking like they think it should and figured their data into a new spreadsheet so we can feed back into everypolitician.

**Comment by zarino** [comment]
Pull request here: https://github.com/theyworkforyou/shineyoureye/pull/37
