### ISSUE TITLE
Styling for all pages to fit in with new homepage

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye#33]
SYE would like the internal pages of the site to match or at least fit in nicely with the new homepage design.

Currently they look like this:

![screen shot 2016-03-21 at 08 39 49](https://cloud.githubusercontent.com/assets/4170351/13913622/91631066-ef40-11e5-9c69-c59973c4fe90.png)

And the homepage looks like this:

![screen shot 2016-03-21 at 08 40 50](https://cloud.githubusercontent.com/assets/4170351/13913710/380fb9f0-ef41-11e5-96d3-15e2b13e11b3.png)

**Comment by zarino** [comment]
Pull request here: https://github.com/theyworkforyou/shineyoureye/pull/58
