### ISSUE TITLE
Remove State Legislators from the homepage

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye#35]
We are no longer supporting state legislatures for Nigeria therefore we need to remove reference to it from the homepage.

**Comment by zarino** [comment]
So, changing it from this:

![screen shot 2016-04-15 at 14 55 42](https://cloud.githubusercontent.com/assets/739624/14564082/db4e9160-031c-11e6-9c9b-b061b429b595.png)

To this?

![screen shot 2016-04-15 at 14 56 15](https://cloud.githubusercontent.com/assets/739624/14564090/deb51d24-031c-11e6-88b0-0059703920ee.png)

**Comment by JenMysoc** [comment]
Parfait!

**Comment by zarino** [comment]
Pull request here: https://github.com/theyworkforyou/shineyoureye/pull/36
