### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by chrismytton** [theyworkforyou/shineyoureye#9]
@JenMysoc Do we want to keep Disqus and preserve the existing comments or switch over to Facebook comments like we did for KuvakaZim?

Some pages do have comments on, e.g. http://www.shineyoureye.org/person/abdullahi-muhammed-wamakko/.

**Comment by JenMysoc** [comment]
Hm, Let me check with them :)

**Comment by JenMysoc** [comment]
Ok They've said that the majority of nigerians are on facebook and won't really use Disqus so please can we just switch to facebook comments?
